#!/bin/bash

packagesApt=(
    "wget"
    "unzip"
    "alacritty"
    "dunst"
    "starship"
    "mpv"
    "thunar"
    "nautilus"
    "mousepad"
    "fonts-noto"
    "fonts-font-awesome"
    "fonts-fira-sans"
    "fonts-fira-code"
    "fonts-firacode-nerd"
    "figlet"
    "vlc"
    "python3-pip"
    "python3-psutil"
    "python3-rich"
    "python3-click"
    "python3-pywal"
    "python3-gi"
    "pavucontrol"
    "tumbler"
    "papirus-icon-theme"
    "breeze-icon-theme"
    "policykit-1-gnome"
    "brightnessctl"
    "manpages"
    "network-manager"
    "network-manager-gnome"
    "gvfs"
    "xdg-user-dirs"
    "xarchiver"
    "thunar-archive-plugin"
    "zip"
    "fuse"
    "libgtk-4-1"
    "libadwaita-1-0"
    "xdg-desktop-portal"
    "gnome-calculator"
    "imagemagick"
    "guvcview"
    "jq"
    "rofi"
    "fastfetch"
    "xclip"
    "pinta"
    "breeze-gtk"
    "qt6ct"
    "stow"
    "firefox"
    "zsh"
    "fzf"
    "zsh-completions"
);

# Hauptpakete installieren
sudo apt-get update
sudo apt-get install -y "${packagesApt[@]}"

# Cleanup
sudo apt-get autoremove -y
